name: Livepeer - branch manifest
description: Generate branch manifest file for livepeer builds strategy
author: hjpotter92

branding:
  icon: code
  color: green

inputs:
  ref-name:
    description: Just the value of `github.ref_name`
    default: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref_name }}
    required: false
  ref:
    description: Full ref path for the branch/tag information
    default: ${{ github.ref }}
    required: false
  commit:
    description: Most recent commit
    default: ${{ (github.ref_type == 'tag' && github.ref_name) || (github.event.pull_request.head.sha || github.sha) }}
    required: false
  bucket-domain:
    description: Google cloud bucket name, optional
    default: build.livepeer.live
    required: false
  bucket-key:
    description: Key inside the `bucket-domain` for generating references
    required: false
  use-prefix:
    description: Use prefix when generating archive names
    default: 'true'
    required: false
  prefix:
    description: Custom prefix to use for archive naming based on project information
    default: livepeer
    required: false
  project-name:
    description: Project name, to be used as gcp bucket root directory
    required: false
  platform:
    description: Supported platforms names. Muliple values can be separated by commas
    default: linux, darwin, windows
    required: false
  architecture:
    description: Supported architectures, comma separated
    default: arm64,amd64
    required: false

outputs:
  manifest-file:
    description: The file created after branch name filter etc.
  release-name:
    description: Name of this release (tag if present, commit otherwise)
  bucket-key:
    description: Key inside the `bucket-domain` for generating references
  project-name:
    description: Project name, to be used as gcp bucket root directory

runs:
  using: node16
  main: 'dist/index.js'
