name: Test the action

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"

jobs:
  test:
    name: Test the action against itself
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Test action
        id: branch-manifest
        uses: ./
        with:
          project-name: ${{ github.event.repository.name }}

      - name: Print manifest file
        run: cat ${{ steps.branch-manifest.outputs.manifest-file }}

      - name: Archive manifest file
        uses: actions/upload-artifact@master
        with:
          name: release-artifacts
          path: ${{ steps.branch-manifest.outputs.manifest-file }}

  codeql:
    name: Analyze project against codeql
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # Check https://github.com/livepeer/go-livepeer/pull/1891
          # for ref value discussion
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set up node
        id: node
        uses: actions/setup-node@v3
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version-file: .tool-versions

      - name: Install dependencies
        if: steps.node.outputs.cache-hit != 'true'
        run: yarn install --immutable --immutable-cache --check-cache

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: typescript
          source-root: src
          # If you wish to specify custom queries, you can do so here or in a config file.
          # By default, queries listed here will override any specified in a config file.
          # Prefix the list here with "+" to use these queries and those in the config file.
          # queries: ./path/to/local/query, your-org/your-repo/queries@main

      - name: Build distributable package
        run: |
          yarn build
          yarn package

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
